version: '3.3'

services:

  api:
      image: node:8.11.3
      volumes:
        - ./api:/api
      env_file:
        - .env
      ports:
        - 8080:8080
      working_dir: /api
      command: bash -c "npm install && npm run start"